### ISSUE TITLE
Add a lightweight, embedded distributed KV database

### ISSUE THREAD

**Issue by DongyuanPan** [apache/rocketmq-mqtt#108]
add a distributed KV database is necessary, we can use it to implement some important features.

1. used to store and manage metadata, such as first topic, wildcard management, subscription relationships, etc.
2. clientid conflict detection. clientId conflict detection has not yet been implemented, because there is no distributed metadata center, only single-machine conflict detection can be achieved.
3. lookup. The lookup component is mainly used to optimize event broadcasting, repeated connection and mutual kicking, and online status query. It is not necessary for the core link of message sending and receiving. The lookup component is actually a KV query. Of course, you can use redis directly, or you can consider the built-in implementation of a simple of memory KV.
4. will and retain can be implement by distributed kv convenient。

**Comment by pingww** [comment]
Could you provide the design details of the internal implementation of this component?

**Comment by DongyuanPan** [comment]
1. The component is implemented as an independent module that can be deployed independently
2. The distributed metadata module of rocketmq-mqtt can use the distributed KV library implemented by Jraft, which is an open source project used by a large number of companies and projects https://www.sofastack.tech/projects/sofa-jraft/jraft-rheakv-user-guide/

**Comment by YYYYWD** [comment]
> 



> 1. The component is implemented as an independent module that can be deployed independently
> 2. The distributed metadata module of rocketmq-mqtt can use the distributed KV library implemented by Jraft, which is an open source project used by a large number of companies and projects https://www.sofastack.tech/projects/sofa-jraft/jraft-rheakv-user-guide/

That sounds like fun. Let's do it

**Comment by DongyuanPan** [comment]
it can be closed.
