### ISSUE TITLE
mqtt demo consume error

### ISSUE THREAD

**Issue by lxflxfeng** [apache/rocketmq-mqtt#111]
MqttProducer.java run sucess
MqttConsumer.java connect success ,but consume error
I opened rocketmq-mqtt remote port debugging and found this 

![image](https://user-images.githubusercontent.com/38031711/171984990-c2f8c6f9-6caf-43ff-abd4-68de1e12f52d.png)
![image](https://user-images.githubusercontent.com/38031711/171984976-6e8ce1eb-b77d-4353-af16-2289ed09a5c9.png)

Hope to help solve, thank you very much

**Comment by YYYYWD** [comment]
I had this problem once. Maybe you can try to clear all the messages under the topic you subscribed to.
