### ISSUE TITLE
Support client online/offline event notification

### ISSUE THREAD

**Issue by ChangingFond** [apache/rocketmq-mqtt#116]

**Comment by pingww** [comment]
It is indeed a good requirement and will be fulfilled

**Comment by ChangingFond** [comment]
@pingww may i give an implementation?

**Comment by DongyuanPan** [comment]
Is there a design document for the current job？

**Comment by ChangingFond** [comment]
@DongyuanPan we have implemented an version, we will commit lately

**Comment by zongtanghu** [comment]
Maybe, we can organize a online meeting to discuss this feature! @DongyuanPan @ChangingFond

**Comment by pingww** [comment]
> 
An important features

**Comment by DongyuanPan** [comment]
@zongtanghu @ChangingFond 

> discuss
How's the feature going?  Yes, if it's convenient, we can organize a meeting to discuss it

**Comment by DongyuanPan** [comment]
> Maybe, we can organize a online meeting to discuss this feature! @DongyuanPan @ChangingFond

How's the feature going? Yes, if it's convenient, we can organize a meeting to discuss it

**Comment by YxAc** [comment]
@pingww @ChangingFond @DongyuanPan @zongtanghu 

Hi there, this feature has numerous applications in Xiaomi's production environment, such as electric vehicles and industrial IoT.

I would like implement this feature using hooks. When a client comes online or goes offline, the MQTT server will generate an event and asynchronously push the event messages to the system topic in RocketMQ through hooks, enabling business subscribers to receive device client online/offline event messages.

The implementation approach primarily involves defining events and hooks, event production, and event handling:
### Event and Hook Definition:
- The `Event` includes specific information about client online and offline events, such as timestamp, clientId, clientIp, etc.
- The `Hook`, which does not use chain calls (as it is unnecessary), mainly focuses on defining the interface.
### Event Production:
- When the MQTT connection CONN is established.
- When the MQTT connection is closed.
### Event Handling:
- Implementing the `HookManager`, which handles event messages by pushing them to RocketMQ in a loop.

**Comment by DongyuanPan** [comment]
Sending messages to a system topic is a good idea, but it's essential to first verify how rocketmq-mqtt handles system topics

**Comment by YxAc** [comment]
> Sending messages to a system topic is a good idea, but it's essential to first verify how rocketmq-mqtt handles system topics

You mean that storing events as `mqtt publish message` to rocketmq lmq, and should allow mqtt clients to consume these events, right? @DongyuanPan
