### ISSUE TITLE
We need a more flexible Meta module

### ISSUE THREAD

**Issue by DongyuanPan** [apache/rocketmq-mqtt#121]
The metadata module uses RheadKV, which cannot flexibly adapt to business needs. Instead, it can directly use JRAFT, and each business realizes its own corresponding state machine .

**Comment by DongyuanPan** [comment]
Maybe we can start a new branch to do this

**Comment by pingww** [comment]
looking forward ...

**Comment by DongyuanPan** [comment]
subTask  #124

**Comment by DongyuanPan** [comment]
subTask #125

**Comment by DongyuanPan** [comment]
subTask #126
