### ISSUE TITLE
Throws the exception Topic does not exist when LmqOffsetStoreManager save offset to broker.

### ISSUE THREAD

**Issue by DongyuanPan** [apache/rocketmq-mqtt#150]
In RocketMQ 4.9.3，the interface updateConsumerOffset  does not check whether the topic exists or not. But in RocketMQ 5.0 do the check. LMQ's topic will not register to namesv， so it will throw error when save offset in rocketmq-mqtt.

**Comment by DongyuanPan** [comment]
We can put the LMQ prefix when storing the Offset Topic of LMQ, just like when storing messages in the Topic.

**Comment by DongyuanPan** [comment]
The broker also needs to do some work synchronously to be compatible with the modification of mqtt

**Comment by pingww** [comment]
> How's this issues going on?

should be fixed in mqtt and broker, soon

**Comment by DongyuanPan** [comment]
> How's this issues going on?
the interface updateConsumerOffset  in RocketMQ 5.0 check whether the topic exists or not.  LMQ's topic will not register to namesv，so the check will always be false.

**Comment by liuwenru** [comment]
但是好像5.x版本的额rocketmq和最新的rocketmq-mqtt还是存在这样的问题😂
