### ISSUE TITLE
To support mutual SSL/TLS 

### ISSUE THREAD

**Issue by DongyuanPan** [apache/rocketmq-mqtt#152]

**Comment by ChangingFond** [comment]
duplicate with this issue https://github.com/apache/rocketmq-mqtt/issues/51

**Comment by DongyuanPan** [comment]
> duplicate with this issue #51

The issue has been updated, unidirectional authentication has been implemented in #51. But mutual SSL/TLS authentication has not been implemented yet.

**Comment by zongtanghu** [comment]
Mutual SSL/TLS authentication , can you put forwoard a pr to fix it?

**Comment by DongyuanPan** [comment]
How's the feature going? @zongtanghu @shendongsd
