### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/rocketmq-mqtt#160]
mvn compile failed

unable to find symbol ,class PostConstruct

**Comment by DongyuanPan** [comment]
I can compile normally on my side. Which branch did you compile and what is the JDK version?

**Comment by Oliverwqcwrw** [comment]
branch: develop
jdk: 1.8.0_201

**Comment by DongyuanPan** [comment]
> 

I can't reproduce it in my environment

**Comment by Oliverwqcwrw** [comment]
jdk8 normally does not have this problem, it may be my environment problem, but above jdk8 may need to add this dependency

**Comment by Kuari** [comment]
I am using the compiled in docker container. The docker image I use is apache/rocketmq:4.9.4, and everything works fine when compiled in the container.

**Comment by pingww** [comment]
The Java Common Annotations Module java.xml.ws.annotation was deprecated in Java version 9 and was removed in java version 11. If this leads to a problem you could try to add javax.annotation.
