### ISSUE TITLE
check upstreamHookResult before enter message handler main logic

### ISSUE THREAD

**Issue by ChangingFond** [apache/rocketmq-mqtt#17]
![image](https://user-images.githubusercontent.com/10083870/157787589-44d53707-3aeb-4203-8cb6-d2366b8c3ee6.png)

Take MqttConnectHandler for example，as show in the above graph. While check upstream hook result return false in code block 2, schedule.schedule() method in code block 1 is unnecessary to run. So, moving code block 2 in front of 1 can reduce run time, maybe just a little, but it is according with what "upstream hook" means.

**Comment by pingww** [comment]
Yes, need to return early
