### ISSUE TITLE
需要一些帮助 Help

### ISSUE THREAD

**Issue by fascinating** [apache/rocketmq-mqtt#181]
你好，这个项目运行起来后，mqtt-example模块里 MQTTProducer创建的消息，MQTTConsumer收不到；请问应该怎么做调整? 使用的版本为 4.9.4
网上的相关资料和文档较少，能不能麻烦抽点时间写个入门文档，当前学习起来有点困难。

**Comment by DongyuanPan** [comment]
你好可以多提供一些信息，按照文档操作，修改MQTTProducer和MQTTConsumer的broker url后 我的环境是没啥问题的。

**Comment by DongyuanPan** [comment]
下面几个步骤比较容易遗漏，可以到broker上确认一下配置，也可以贴一下mqtt的conf 我们对比一下
![image](https://user-images.githubusercontent.com/18721508/219576077-a3861ac0-f435-4c54-bd86-894c18ae0560.png)

**Comment by fascinating** [comment]
> 下面几个步骤比较容易遗漏，可以到broker上确认一下配置，也可以贴一下mqtt的conf 我们对比一下 ![image](https://user-images.githubusercontent.com/18721508/219576077-a3861ac0-f435-4c54-bd86-894c18ae0560.png)

十分感谢提醒，配置是按说明配置的，原因是我订阅了在管理台创建的主题，能发送消息，但是MQTTConsumer收不到；然后按创建eventNotifyRetryTopic的方式创建新的主题，就可以订阅到了。
