### ISSUE TITLE
Confusing why append '/' to the end of topic name? 

### ISSUE THREAD

**Issue by ferrirW** [apache/rocketmq-mqtt#19]
Have not find related explain, please give some description.

https://github.com/apache/rocketmq-mqtt/blob/9939eabad05dced3fb202804de8c3942764986cd/mqtt-common/src/main/java/org/apache/rocketmq/mqtt/common/util/TopicUtils.java#L27-L44

**Comment by tianliuliu** [comment]
ping @pingww

**Comment by pingww** [comment]
The main reason is to format it into a fixed format. As for the addition of a /, the reason is that there is a matching path in the trie, which can indeed be optimized.

**Comment by ferrirW** [comment]
ok, thanks for answering.

And found some code can be optimized:

1. ADDFLAG & JINFLAG should be replaced with PLUS_SIGN & NUMBER_SIGN refer to unicode

2. Some redundant containsKey before putIfAbsent()

3. buildIntanceName -> buildInstanceName

4.  TopicUtils.isMatch("t/t1/t2/", "t/#/t2/") should be false but return true now.(I know some client will do this check like poho, however, it is better for the server to do a validation as well)

**Comment by pingww** [comment]
"t/#/t2/"   is not valid according to the mqtt protocol

**Comment by ferrirW** [comment]
> "t/#/t2/" is not valid according to the mqtt protocol

yes, I just want to suggest server should do this check anyway, like: https://github.com/apache/rocketmq-mqtt/pull/25#discussion_r825635672
