### ISSUE TITLE
rocketmq-mqtt1.0.1 启动后

### ISSUE THREAD

**Issue by gzllSnail** [apache/rocketmq-mqtt#190]
rocketmq-mqtt 启动以后 
在mqtt-example中修改统一的Topic以后
RocketMQConsumer 可以收到MqttProducer和RocketMQProducer 的消息
但是
MqttConsumer 无法接收到MqttProducer和RocketMQProducer 的消息
rocketmq-mqtt 是否支持 RocketMQProducer 转换 mqtt的能力 ？
需要怎么做？

**Comment by 13656663676** [comment]
使用mqtt 能力，MqttProducer 发送消息成功，MqttConsumer无法接收到同一个topic的信息，是否支持MqttConsumer？？改功能是否有问题？

**Comment by gzllSnail** [comment]
我这边同样是这个问题，不知道是不是不支持将RocketMQProducer 转换mqtt ，如果你发现了这个问题的解决方法，麻烦写出来交流一下

**Comment by DongyuanPan** [comment]
![image](https://user-images.githubusercontent.com/18721508/234503193-bdd076a9-469f-4005-a37d-7a849c77da03.png)
可以检查一下MQTT相关的配置时是否设置正确，MQTT 例子里面使用的firstTopic需要提前在途中的立方设置
