### ISSUE TITLE
rocketmq-mqtt 1.0.1和1.0.2-SNAPSHOT MqttConsumer功能无法使用，求解决方法

### ISSUE THREAD

**Issue by 13656663676** [apache/rocketmq-mqtt#192]
mqtt测试 MqttProducer 可以正常发送信息，MqttConsumer无法接收同一个topic信息，求解决方法

**Comment by DongyuanPan** [comment]
你好，可以检查一下broker上相应的资源创建了吗？kv相关存储firstTopic的信息设置了没？

**Comment by DongyuanPan** [comment]
> 使用mqtt可以生产消息，mqtt 无法消费，但是可以用mq 客户端消费

检查一下RMQ是不是没开启LMQ的特性



> 还有请教一个问题，mqtt支持设置消息的存活时间吗？比如说一个消息在指定时间内没有被消费自动过期的这种

MQTT 5.0支持消息的TTL，目前RocketMQ-MQTT支持的是 3.3.1 协议还不支持
