### ISSUE TITLE
Build Fails on ARM MAC

### ISSUE THREAD

**Issue by meshpaul** [apache/rocketmq-mqtt#193]
1.  When building on ARM MAC required to add `-Dos.arch=x86_64` to bypass protobuff build issues
2. When this is passed the next issue is related to this https://github.com/apache/rocketmq-mqtt/issues/160 having PostConstruct deps are missing from POM.xml of related projects.  
3. Any particular reason the `javax.annotation` deps are missing they are not part of ANY JDK it looks like these somehow on your build/classpath in project authors set-up and the required build instructions/set-up is then missing.
```
                   <dependency>
                        <groupId>javax.annotation</groupId>
                        <artifactId>javax.annotation-api</artifactId>
                        <version>1.3.2</version>
                    </dependency>
```
4. Also going back to item 2 pointing to issue is this project tied to https://github.com/apache/rocketmq-mqtt/issues/160#issuecomment-1329993294     RocketMQ 4.9.4 and must be build in Docker if yes any hint in setting this up is appreciated?

Thank you

**Comment by pingww** [comment]
The Java Common Annotations Module java.xml.ws.annotation was deprecated in Java version 9 and was removed in java version 11. If this leads to a problem you could try to add javax.annotation.

**Comment by meshpaul** [comment]
No these are two different deps `javax.annotation` is not the same as `java.xml.ws.annotation` my point is that  your project is either missing proper build instructions in your [readme](https://github.com/apache/rocketmq-mqtt/blob/e0c62d476c92ff5de73b314d7284bd3877b1bc45/README.md?plain=1#L28-L40).   or `pom.xml` needs to have correct dependency added since other folks were able build this only while in they have `javax.annotation` deps on classpath https://github.com/apache/rocketmq-mqtt/issues/160#issuecomment-1329993294
