### ISSUE TITLE
如何自动创建topic

### ISSUE THREAD

**Issue by HiSuperPotato** [apache/rocketmq-mqtt#195]
是否有办法在 MqttProducer 在 mqttClient.publish(topic, message)  发送消息时候，如果没有提前创建topic则自动创建topic，而不需要初始化  sh mqadmin updatetopic -c DefaultCluster -t xxxxx -n xxxxxx

**Comment by pingww** [comment]
Just confirm whether the RMQ version supports automatic topic creation

**Comment by HiSuperPotato** [comment]
> Just confirm whether the RMQ version supports automatic topic creation
我使用的版本是 apache/rocketmq 4.93-----rocketmq-mqtt 1.0.0   roketmq

**Comment by HiSuperPotato** [comment]
谢谢你的回复
      我有个疑问 RMQ 版本为 4.93  MQTT 版本为 1.0.0 经测试在RMQ开启自动创建topic情况下（autoCreateTopicEnable=true）mq确实可以自动创建topic并发布消息  但是mqtt却不能在未提前创建的topic发布消息 是否是我使用方式有问题 如果有解决方式请指教

**Comment by pingww** [comment]
> 谢谢你的回复 我有个疑问 RMQ 版本为 4.93 MQTT 版本为 1.0.0 经测试在RMQ开启自动创建topic情况下（autoCreateTopicEnable=true）mq确实可以自动创建topic并发布消息 但是mqtt却不能在未提前创建的topic发布消息 是否是我使用方式有问题 如果有解决方式请指教

mqtt目前需要在namesrv上手动添加topic到kv配置，后续会优化一下这块

**Comment by HiSuperPotato** [comment]
好的 谢谢
