### ISSUE TITLE
启动后疯狂报错。mqtt.log

### ISSUE THREAD

**Issue by imgoddqp** [apache/rocketmq-mqtt#198]
version ： rocketmq-5.1.1
mqtt.log screenshot 如下：
但是 mqtt 消息收发正常（非 will、retain）
<img width="1254" alt="image" src="https://github.com/apache/rocketmq-mqtt/assets/24971545/fcfaef84-8c2f-466d-89c0-ac3d9ea3e71f">

**Comment by imgoddqp** [comment]
> 

麻烦问下端口是nameserv的还是 broker 的？还是？

**Comment by imgoddqp** [comment]
> 你这个问题我曾经发现过 原因是配置搞错了 就是 sh mqadmin updateKvConfig -s LMQ -k ALL_FIRST_TOPICS -v {topic1,topic2} -n {namesrv} 这个 ALL_FIRST_TOPICS 的配置， 你是不是把 eventNotifyRetryTopic clientRetryTopic 这些topic也配置进去了？ 这2个不能配置 然后的话就一直死循环消费错误的数据

感谢大佬指点，我确实这么配置了，然而修改重新配置了还是不行ಥ_ಥ

**Comment by wljin321** [comment]
> 

应该是 mqtt  meta.conf 中的selfAddress 地址 启动了多少配置多少

**Comment by imgoddqp** [comment]
> 应该是 mqtt meta.conf 中的selfAddress 地址 启动了多少配置多少
大佬我有点搞不清楚端口分别应该是什么

**Comment by wljin321** [comment]
> 

不会吧  meta.conf中 的 selfAddress 你不配置端口的话start meta 会报错的  
比如 selfAddress=localhost:8080  这样才行

**Comment by imgoddqp** [comment]
> > 
> 
> 不会吧 meta.conf中 的 selfAddress 你不配置端口的话start meta 会报错的 比如 selfAddress=localhost:8080 这样才行

好神奇，我启动成功了。还能收发消息
那我应该给8080是吗？这个端口是干嘛的呢？固定的一定是8080吗？是 rocketmq-mqtt本身能搞成集群？
不过我服务器上有 rocketmq-dashboard 他的端口是8080

**Comment by wljin321** [comment]
> 好神奇，我启动成功了。还能收发消息 那我应该给8080是吗？这个端口是干嘛的呢？固定的一定是8080吗？是 rocketmq-mqtt本身能搞成集群？ 不过我服务器上有 rocketmq-dashboard 他的端口是8080
应该启动有报错的 你没看到 在 start_out.log日志文件里  
这个端口的meta服务的端口  可以随便改的 只要配置一致 就行  和metaAddr一致

**Comment by imgoddqp** [comment]
感谢大佬    已解决！！
