### ISSUE TITLE
请教一个关于部署方面的问题

### ISSUE THREAD

**Issue by HiSuperPotato** [apache/rocketmq-mqtt#200]
**部署环境：**

1. RoketMQ版本4.93 部署方式docker
2. Mqtt版本1.0.0  编译部署 
3. 部署环境 centos 8.5

- rocketmq 容器用 --network host 主机网络模式启动
- mqtt 配置 NAMESRV_ADDR= 127.0.0.1:9876

**问题**
环境部署好之后能正常接收和发送消息 ,如果发生物理服务器下电（断电）的情况 我重启docker RocketMq 容器 和 mqtt 服务 就会发生消息能正常发送但是接收不到的情况，观察日志并无报错信息，特殊的部署环境会时常有服务器上下电的情况 。

**Comment by pingww** [comment]
升级RMQ到最新版本看看

**Comment by HiSuperPotato** [comment]
现在将RocketMQ 版本升级到5.1.0 问题已解决 thanks
