### ISSUE TITLE
使用LMQ  当mqtt接入的设备太多时，mq的store/consumequeue存储目录会产生大量的lmq消费队列目录 ，这块会不会超出系统限制或者有其他的性能问题

### ISSUE THREAD

**Issue by wljin321** [apache/rocketmq-mqtt#202]
一个文件夹中子目录的数量会有限制

**Comment by pingww** [comment]
这个要依赖RMQ的百万队列能力，社区开源计划中

**Comment by DongyuanPan** [comment]
> > 这个要依赖RMQ的百万队列能力，社区开源计划中
> 
> @pingww 是指基于 rocksdb 的方案吗

@ferrirW 是的，目前正在开源流程中

**Comment by ferrirW** [comment]
> @ferrirW 是的，目前正在开源流程中

期待

**Comment by hill007299** [comment]
详见rip 66 https://docs.google.com/document/d/e/2PACX-1vT3QJ8XDbKi8HQKaIDodOD4vIV0-xlERFtg8Ed3FsYUi7IfRs5JVKjElGaxpk-0ErH0xdWT0Vv-a1u5/pub
