### ISSUE TITLE
请问LMQ是否支持10W TOPIC？感谢

### ISSUE THREAD

**Issue by lzkisok** [apache/rocketmq-mqtt#211]
请问LMQ是否支持10W TOPIC，非常感谢

**Comment by DongyuanPan** [comment]
这个依赖于RMQ的能力，目前RMQ基于KV存储队列元数据的功能已经开源，底层能力已经能够支持几十万的Topic。不过，RMQ目前还需要进行一些适配，以适应LMQ的特性。

**Comment by lzkisok** [comment]
目前KV存储没有问题，我们看到RMQ broker和namesrv的心跳会带上有所的TOPIC信息，namesrv进行decoder解码默认是16M
1，心跳消息体过大是否对网络和解码压力过大？
2，频繁进行大量数据的心跳是否合理？

**Comment by DongyuanPan** [comment]
> 目前KV存储没有问题，我们看到RMQ broker和namesrv的心跳会带上有所的TOPIC信息，namesrv进行decoder解码默认是16M

这个是RocketMQ 注册namesrv的通用行为，对于大量的Topic 如果都去注册确实会有问题。目前RocketMQ 里面的LMQ特性的实现是不会注册NameSrv的。
