### ISSUE TITLE
当MQTT设备数量特别多，消息特别频繁的时候，notify的RPC 因为是每台服务器都通知的，每台服务器接受notify QPS会特别高

### ISSUE THREAD

**Issue by lzkisok** [apache/rocketmq-mqtt#212]
比如10W台设备，每台设备每秒下发一个消息，每台服务器的notify RPC就是10W QPS

**Comment by DongyuanPan** [comment]
1. 并不是每一条消息都会产生事件，事件可以合并减少事件的数量
2. 彻底解决广播问题，需要实现路由查找模块。目前开源还没有这样能力，后续会开源。
3. 目前开源广播放大比和集群节点数量有关

**Comment by lzkisok** [comment]
麻烦问下，彻底解决广播问题，大概什么时候开源，谢谢

**Comment by pingww** [comment]
> 比如10W台设备，每台设备每秒下发一个消息，每台服务器的notify RPC就是10W QPS

1）这10W QPS并不是一台服务器负责，而是通过RMQ消费负载均衡的notify
2）这个notify只是topic名称，没有消息体
3）notify可以按批（pull）合并降低qps
