### ISSUE TITLE
当生产者和消费者的Qos等级不同时，当前似乎没有实现降级

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq-mqtt#214]
当生产者和消费者的Qos等级不同时，当前似乎没有实现降级

这块社区是如何考虑这个问题的？ 

http://www.taichi-maker.com/homepage/esp8266-nodemcu-iot/iot-tuttorial/mqtt-tutorial/mqtt-qos/
https://www.emqx.com/zh/blog/an-introduction-to-subscription-options-in-mqtt

**Comment by DongyuanPan** [comment]
MQTT协议里面client和server角色是不严格区分的，是可以交换的。所以这个QOS我们理解是一个双方交互的一个协议规范，例如需不需要恢复ACK等。所以发送的时候由发送者在message里面设置qos，表示要和服务端以相应的qos进行交互。作为接收者的时候，通过subscribe 告诉服务器，接收者想要以何种qos进行交互，随后服务端给接收者推送消息，就会按照这个进行。

**Comment by DongyuanPan** [comment]
也就是说，是独立的

**Comment by leizhiyuan** [comment]
emqx的实现
<img width="790" alt="image" src="https://github.com/apache/rocketmq-mqtt/assets/2684384/784702dd-b89b-4354-9317-fd28d9a1d5a3">

是取了消息和订阅者的min，实测也是这样的。

这块mqtt文档中，没有说的很明显。

**Comment by leizhiyuan** [comment]
mqtt的文档这里确实没有看到有这个说法，可以先保持这样倒也可以。

**Comment by leizhiyuan** [comment]
https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csd02/mqtt-v3.1.1-csd02.html

<img width="785" alt="WeChatWorkScreenshot_23e4990e-4793-4463-b250-a0078f281208" src="https://github.com/apache/rocketmq-mqtt/assets/2684384/bb6c0dc4-a75a-4e0a-9152-69ec44c58b64">

**Comment by DongyuanPan** [comment]
哦哦，可能我们说的不是一个事情。EMQ的意思是，最终的QOS是服务端能够支持的最大QOS和设备请求QOS的最小值。例如服务端只支持QOS1，但是设备发指定了QOS2。这个时候应该直接返回错误的（例如MQTT5.0 协议支持sub的时候，给回复告诉设备服务端能够支持的最大QOS是多少），他们是实现一个降级，就是降级到QOS 1进行通行。

**Comment by DongyuanPan** [comment]
> 设备

可以是生产者、也可以是消费者

**Comment by DongyuanPan** [comment]
> https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csd02/mqtt-v3.1.1-csd02.html
> 
> <img alt="WeChatWorkScreenshot_23e4990e-4793-4463-b250-a0078f281208" width="785" src="https://user-images.githubusercontent.com/2684384/277316638-bb6c0dc4-a75a-4e0a-9152-69ec44c58b64.png">

这个就是我之前提到的情况，生产和消费是互相独立的，谁来发、谁来收，就按照谁的QOS为准去交互。即：作为接收者的时候，通过subscribe 告诉服务器，接收者想要以何种qos进行交互，随后服务端给接收者推送消息，就会按照这个进行。

**Comment by leizhiyuan** [comment]
please assign to @zzjcool

**Comment by lizhanhui** [comment]
> 也就是说，是独立的

我觉得你的理解和Spec是有偏差的。应该有个downgrade的过程： https://cedalo.com/blog/understanding-mqtt-qos/

<img width="855" alt="image" src="https://github.com/user-attachments/assets/5a7bd6c1-9af1-4138-9005-cde2e4b70cf1">
