### ISSUE TITLE
安装配置好之后使用mqttx测试连接不上

### ISSUE THREAD

**Issue by EssinZhang** [apache/rocketmq-mqtt#216]
RocketMQ 版本5.1.4   RocketMQ-mqtt 版本 1.0.2

![image](https://github.com/apache/rocketmq-mqtt/assets/35253559/37a6fd99-f312-477a-ae5d-d65300970fc7)

这是日志
![image](https://github.com/apache/rocketmq-mqtt/assets/35253559/1c015357-f4da-4a16-8a25-5ac65382e908)

这是mqtt的配置文件
![image](https://github.com/apache/rocketmq-mqtt/assets/35253559/2693f553-0d40-4c93-882b-fe6ffa76fbcd)

我对了好多遍用户名和密码是对的没错

**Comment by DongyuanPan** [comment]
> 密码
参考示例代码，密码需要加签
        connOpts.setUserName(System.getenv("username"));
        connOpts.setPassword(HmacSHA1Util.macSignature(clientId, System.getenv("password")).toCharArray());

**Comment by DongyuanPan** [comment]
密码
参考示例代码，密码需要加签
connOpts.setUserName(System.getenv("username"));
connOpts.setPassword(HmacSHA1Util.macSignature(clientId, System.getenv("password")).toCharArray());

**Comment by EssinZhang** [comment]
奥，那就是没办法用mqttx直接进行收发测试了

**Comment by EssinZhang** [comment]
> 密码 参考示例代码，密码需要加签 connOpts.setUserName(System.getenv("username")); connOpts.setPassword(HmacSHA1Util.macSignature(clientId, System.getenv("password")).toCharArray());

有交流群么？

**Comment by DongyuanPan** [comment]
> 奥，那就是没办法用mqttx直接进行收发测试了

可以的哈，你求出加签后的密码，直接写在mqttx 上就行

**Comment by DongyuanPan** [comment]
> > 密码 参考示例代码，密码需要加签 connOpts.setUserName(System.getenv("username")); connOpts.setPassword(HmacSHA1Util.macSignature(clientId, System.getenv("password")).toCharArray());
> 
> 有交流群么？

看一些置顶的ISSUES，里面有一个群二维码

**Comment by EssinZhang** [comment]
> > 奥，那就是没办法用mqttx直接进行收发测试了
> 
> 可以的哈，你求出加签后的密码，直接写在mqttx 上就行

右边三种加签后的密码都试了都不行，人麻了
![image](https://github.com/apache/rocketmq-mqtt/assets/35253559/fbc60144-43fb-4fff-943b-0987fbc406cf)

**Comment by EssinZhang** [comment]
> > > 密码 参考示例代码，密码需要加签 connOpts.setUserName(System.getenv("username")); connOpts.setPassword(HmacSHA1Util.macSignature(clientId, System.getenv("password")).toCharArray());
> > 
> > 
> > 有交流群么？
> 
> 看一些置顶的ISSUES，里面有一个群二维码

那个二维码是7天的，过期了，我才再次问的

**Comment by ShiXulu** [comment]
如此的难用

**Comment by ShiXulu** [comment]
> > > 奥，那就是没办法用mqttx直接进行收发测试了
> > 
> > 
> > 可以的哈，你求出加签后的密码，直接写在mqttx 上就行
> 
> 右边三种加签后的密码都试了都不行，人麻了 ![image](https://private-user-images.githubusercontent.com/35253559/285382134-fbc60144-43fb-4fff-943b-0987fbc406cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTk5MzMsIm5iZiI6MTcwMjU1OTYzMywicGF0aCI6Ii8zNTI1MzU1OS8yODUzODIxMzQtZmJjNjAxNDQtNDNmYi00ZmZmLTk0M2ItMDk4N2ZiYzQwNmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEzMTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZDYzOTUwZmU5NDk0ZDVkMGYzODA5NWRmMTJmOWViZTY1NGIxZjA2MzU3ODAzMDM0MDM0Mjg5NDEwOTU0M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cZ6TFoPJca8GMCgjqjyAet9o0b9-xb_9x0hgx6oBw1g)

我也遇到了，兄弟连上了吗？

**Comment by ShiXulu** [comment]
example里面抠出来的不行，但是在这个地方抠出来的密文是可以连接的：
org.apache.rocketmq.mqtt.common.util.HmacSHA1Util#validateSign，直接取能返回true的加签密文，如下图：
![WeChat4900ca278b62190ca4c5c896a2f5c0ac](https://github.com/apache/rocketmq-mqtt/assets/9426555/e25c4e0e-7f59-48c4-b592-3f31c9c28515)

**Comment by EssinZhang** [comment]
> example里面抠出来的不行，但是在这个地方抠出来的密文是可以连接的： org.apache.rocketmq.mqtt.common.util.HmacSHA1Util#validateSign，直接取能返回true的加签密文，如下图： ![WeChat4900ca278b62190ca4c5c896a2f5c0ac](https://private-user-images.githubusercontent.com/9426555/290711887-e25c4e0e-7f59-48c4-b592-3f31c9c28515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDk0ODYsIm5iZiI6MTcwMjYwOTE4NiwicGF0aCI6Ii85NDI2NTU1LzI5MDcxMTg4Ny1lMjVjNGUwZS03ZjU5LTQ4YzQtYjU5Mi0zZjMxYzljMjg1MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMDI1OTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmExMDNiYmQ3NTIxNDQwYTAxOTRiOGYyNjg2ZjViZmEwNmVkZDA0OTc5MzBhMWY2MDA2ZmU4MzNmNmMyMzE1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lStDqpE-rsV3N8XrpTeX1B4MUhFJ0EsXPDSdvRKN7YU)

兄弟厉害，我们直接改用RabbitMQ的mqtt插件了，感觉RocketMQ的像半成品，好多issue没解决

**Comment by yuhang1028** [comment]
![image](https://github.com/apache/rocketmq-mqtt/assets/46080938/9a026fb0-8e6a-49b2-98ff-66dfdd521c9f)
大佬这该怎么可解决

**Comment by DongyuanPan** [comment]
> > > 奥，那就是没办法用mqttx直接进行收发测试了
> > 
> > 
> > 可以的哈，你求出加签后的密码，直接写在mqttx 上就行
> 
> 右边三种加签后的密码都试了都不行，人麻了 ![image](https://private-user-images.githubusercontent.com/35253559/285382134-fbc60144-43fb-4fff-943b-0987fbc406cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjg0NTEsIm5iZiI6MTcwMzEyODE1MSwicGF0aCI6Ii8zNTI1MzU1OS8yODUzODIxMzQtZmJjNjAxNDQtNDNmYi00ZmZmLTk0M2ItMDk4N2ZiYzQwNmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAzMDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYzM4ZWQzZGJhZjIwZjE4NGY1NGFiOTQ3YTMzNTM2ZjQ0MDU4NTc0MmU1YWVhNjQ0ZjhhYmE0ZmM1YzI1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._R_Hw3LXxVyDviU0wWHS0nkJMkAKjc--chDudgYBEtc)

老哥，你这里输入了char array，不要求char array，输入转换前的字符串。mqttx 会再求一次的

**Comment by ShiXulu** [comment]
> > example里面抠出来的不行，但是在这个地方抠出来的密文是可以连接的： org.apache.rocketmq.mqtt.common.util.HmacSHA1Util#validateSign，直接取能返回true的加签密文，如下图： ![WeChat4900ca278b62190ca4c5c896a2f5c0ac](https://private-user-images.githubusercontent.com/9426555/290711887-e25c4e0e-7f59-48c4-b592-3f31c9c28515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDk0ODYsIm5iZiI6MTcwMjYwOTE4NiwicGF0aCI6Ii85NDI2NTU1LzI5MDcxMTg4Ny1lMjVjNGUwZS03ZjU5LTQ4YzQtYjU5Mi0zZjMxYzljMjg1MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMDI1OTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmExMDNiYmQ3NTIxNDQwYTAxOTRiOGYyNjg2ZjViZmEwNmVkZDA0OTc5MzBhMWY2MDA2ZmU4MzNmNmMyMzE1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lStDqpE-rsV3N8XrpTeX1B4MUhFJ0EsXPDSdvRKN7YU)
> 
> 兄弟厉害，我们直接改用RabbitMQ的mqtt插件了，感觉RocketMQ的像半成品，好多issue没解决

大厂的话，建议rocketmq的解决方案，国产化是大趋势啊，往后阵营割裂会越来越严重。另外，rabbit量大的时候说是没rocket猛。
希望国产软件越来越好

**Comment by EssinZhang** [comment]
> > > example里面抠出来的不行，但是在这个地方抠出来的密文是可以连接的： org.apache.rocketmq.mqtt.common.util.HmacSHA1Util#validateSign，直接取能返回true的加签密文，如下图： ![WeChat4900ca278b62190ca4c5c896a2f5c0ac](https://private-user-images.githubusercontent.com/9426555/290711887-e25c4e0e-7f59-48c4-b592-3f31c9c28515.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDk0ODYsIm5iZiI6MTcwMjYwOTE4NiwicGF0aCI6Ii85NDI2NTU1LzI5MDcxMTg4Ny1lMjVjNGUwZS03ZjU5LTQ4YzQtYjU5Mi0zZjMxYzljMjg1MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMDI1OTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmExMDNiYmQ3NTIxNDQwYTAxOTRiOGYyNjg2ZjViZmEwNmVkZDA0OTc5MzBhMWY2MDA2ZmU4MzNmNmMyMzE1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lStDqpE-rsV3N8XrpTeX1B4MUhFJ0EsXPDSdvRKN7YU)
> > 
> > 
> > 兄弟厉害，我们直接改用RabbitMQ的mqtt插件了，感觉RocketMQ的像半成品，好多issue没解决
> 
> 大厂的话，建议rocketmq的解决方案，国产化是大趋势啊，往后阵营割裂会越来越严重。另外，rabbit量大的时候说是没rocket猛。 希望国产软件越来越好

要不是我们有开源组件使用限制，早就直接用专业的EMQX了，还用这个，人EMQX是专门做物联网的，而且人家就是杭州的公司也是国产的
