### ISSUE TITLE
codeCov is not very optimistic, need to increase code coverage

### ISSUE THREAD

**Issue by tianliuliu** [apache/rocketmq-mqtt#22]
in branch main codeCov 20%
 need add code coverage
![image](https://user-images.githubusercontent.com/13758677/157836583-420803dc-d050-4eb3-afd7-0fd856712fbc.png)

**Comment by YxAc** [comment]
I am interested in this and willing to enhance it for some time in the future，may I？

**Comment by tianliuliu** [comment]
> I am interested in this and willing to enhance it for some time in the future，may I？
[YxAc](https://github.com/YxAc)，You are very welcomed to participate in the joint construction of rocketmq-mqtt !!!

**Comment by YxAc** [comment]
Be happy that the problem is finally finished, :-), thanks @pingww
