### ISSUE TITLE
rocket-mqtt部置在多台服务器上，如何配置接入实现负载均衡

### ISSUE THREAD

**Issue by vinnyyou** [apache/rocketmq-mqtt#224]
共用一个rocketmq集群，rocketmq-mqtt部署在多台服务器上，每台rocketmq-mqtt设置相同的first topic, 不同的 notify topic，设备接入不同的rocketmq-mqtt服务器，这样是否行?

**Comment by DongyuanPan** [comment]
If different notification topics are configured, then each rocketmq-mqtt event notification will be independent, and they will appear to be independent clusters. Even if the same first topic is set, there will be problems. It is recommended to use traditional load balancing to implement load balancing of mqtt service.
