### ISSUE TITLE
最新拉的代码pom文件有版本冲突

### ISSUE THREAD

**Issue by EssinZhang** [apache/rocketmq-mqtt#225]
![image](https://github.com/apache/rocketmq-mqtt/assets/35253559/b63639e2-cbbf-47e2-a489-fbda7f5c3896)
我把1.2.3的删了就行了
估计是官方不小心合分支疏漏了

**Comment by DongyuanPan** [comment]
Welcome to submit PR to fix it. You can submit it to the develop branch.
