### ISSUE TITLE
能增加web端支持吗？有计划吗

### ISSUE THREAD

**Issue by cwj12345612** [apache/rocketmq-mqtt#230]
可以增加对web端的支持吗？和emqx一样能在前端使用mqtt.js连接。

**Comment by DongyuanPan** [comment]
> 可以增加对web端的支持吗？和emqx一样能在前端使用mqtt.js连接。

可以的，现在是支持mqtt.js的

**Comment by cwj12345612** [comment]
> > 可以增加对web端的支持吗？和emqx一样能在前端使用mqtt.js连接。
> 
> 可以的，现在是支持mqtt.js的

那前端端口是多少？1883？使用什么协议访问？

**Comment by DongyuanPan** [comment]
> > > 可以增加对web端的支持吗？和emqx一样能在前端使用mqtt.js连接。
> > 
> > 
> > 可以的，现在是支持mqtt.js的
> 
> 那前端端口是多少？1883？使用什么协议访问？

tcp 是 1883、ssl 是 8883、ws是8888

**Comment by cwj12345612** [comment]
> > > > 可以增加对web端的支持吗？和emqx一样能在前端使用mqtt.js连接。
> > > 
> > > 
> > > 可以的，现在是支持mqtt.js的
> > 
> > 
> > 那前端端口是多少？1883？使用什么协议访问？
> 
> tcp 是 1883、ssl 是 8883、ws是8888

ok谢谢

**Comment by cwj12345612** [comment]
> > > > 可以增加对web端的支持吗？和emqx一样能在前端使用mqtt.js连接。
> > > 
> > > 
> > > 可以的，现在是支持mqtt.js的
> > 
> > 
> > 那前端端口是多少？1883？使用什么协议访问？
> 
> tcp 是 1883、ssl 是 8883、ws是8888

ok  谢谢
