### ISSUE TITLE
enableLmq = true 已开启，mqtt发布的消息，mqttConsumer订阅不到消息。使用其他三方mqtt服务，mqttConsumer代码就可以。而且使用mqttConsumer不需要配置consumerGroup？

### ISSUE THREAD

**Issue by youqichun** [apache/rocketmq-mqtt#234]

**Comment by DongyuanPan** [comment]
检查一下系统Topic是否创建，事件通知、重试topic等
检查一下first topic是否提前创建，并配置到namesrv 的kv里面。
如果通配符用到了，也需要配置到kv里面。

**Comment by DongyuanPan** [comment]
而且使用mqttConsumer不需要配置consumerGroup？
不需要，MQTT协议没有consumerGroup的概念
