### ISSUE TITLE
Develop branch startup exception

### ISSUE THREAD

**Issue by yx9o** [apache/rocketmq-mqtt#274]
Hi, community, I got an unexpected exception when running the development branch in the ide.

Exception:
<img width="1151" alt="image" src="https://github.com/apache/rocketmq-mqtt/assets/12792261/c4ef2dec-abd2-4ad7-ba29-590918cf7ce2">

Steps to reproduce:
- Start a new RocketMQ-ns
- Start a new RocketMQ-broker
- Start RocketMQ-mqtt

Cause analysis:
During initialization in `MetaPersistManagerSample`, the information of the consumer group `CID_RMQ_SYS_mqtt_event` will be dynamically obtained. At this time, the broker will return `CODE: 206 DESC: the consumer group[CID_RMQ_SYS_mqtt_event] not online BROKER:`. Here, if code!=200 is judged, an `MQBrokerException` exception will be thrown. 
The first execution of `refreshMeta()` in init() does not catch the exception, so the startup will fail.
<img width="1016" alt="image" src="https://github.com/apache/rocketmq-mqtt/assets/12792261/555b6e93-220b-4f10-ad6b-58ba38c12df8">

**Comment by DongyuanPan** [comment]
Yes, MetaPersistManagerSample and NotifyManager should be in a certain order

**Comment by yx9o** [comment]
Fixed by #276.
