### ISSUE TITLE
rockermq5.2.0 + mqtt 1.0.2  可以生产消息，无法消费

### ISSUE THREAD

**Issue by tcjc5214** [apache/rocketmq-mqtt#292]
topic 已经初始化，但broke 依旧报错  ，
![image](https://github.com/apache/rocketmq-mqtt/assets/21101930/473a8df1-6e81-495c-979a-11549766b01d)，这个L%LMQ%TestTopic%r2%  需要手动创建吗 ，TestTopic 已经手动创建

**Comment by ChangingFond** [comment]
is rocketmq enabled lmq？check your broker.conf

enableLmq = true
enableMultiDispatch = true

**Comment by tcjc5214** [comment]
> is rocketmq enabled lmq？check your broker.conf
> 
> enableLmq = true enableMultiDispatch = true

yes ,my broker.conf is  
![image](https://github.com/apache/rocketmq-mqtt/assets/21101930/41673a0e-92b1-4be2-b8fe-e025aa30ea44)

**Comment by DongyuanPan** [comment]
> > is rocketmq enabled lmq？check your broker.conf
> > enableLmq = true enableMultiDispatch = true
> 
> yes ,my broker.conf is ![image](https://private-user-images.githubusercontent.com/21101930/344085853-41673a0e-92b1-4be2-b8fe-e025aa30ea44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjE5MTcsIm5iZiI6MTcxOTU2MTYxNywicGF0aCI6Ii8yMTEwMTkzMC8zNDQwODU4NTMtNDE2NzNhMGUtOTJiMS00YmUyLWI4ZmUtZTAyNWFhMzBlYTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA4MDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNTAzNmVhYTkyYWVjZmJmODdjOWUyZGI0ODFlYjg5MmEwY2VjOWZmODA1YmQ3MzkzNzBhYjk5YzgzZjg2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avbdBXahmFlb3YXkRopGtILM2HSX-wGbwAro31-H7V0)

plz use getBrokerConfig to see these two configurations at runtime

**Comment by DongyuanPan** [comment]
There are bugs in rocketmq 5.2.0 that cause properties of mqtt messages stored in mq to be corrupted. The rocketmq 5.1.4 + roketmq-mqtt develop branch can be used
