### ISSUE TITLE
rocketmq 5.2.0 + mqtt 1.0.2 启动mqtt会报大量的TopicUtils.decode空指针，并且通过arthas查看是反复消费推送MessageEvent -> brokerName=@String[MacBook-Pro.local]，其他信息都为空，这个是我配置问题还是代码问题？

### ISSUE THREAD

**Issue by fengzhaowang** [apache/rocketmq-mqtt#297]

**Comment by fengzhaowang** [comment]
![Uploading WX20240630-145736@2x.png…]()

**Comment by DongyuanPan** [comment]
rmq 5.2.0 is not yet compatible with rocketmq-mqtt, but this error will not be thrown. It should be a configuration and usage issue

**Comment by fengzhaowang** [comment]
那我应该用哪个版本的rocketmq去配合1.0.1的mqtt去使用

**Comment by ChangingFond** [comment]
@fengzhaowang you can use rocketmq 5.1.4

**Comment by fengzhaowang** [comment]
[mqtt问题重现操作.txt](https://github.com/user-attachments/files/16047572/mqtt.txt)
问题还依然在，已经换成5.1.4版本，具体操作放在附件中

**Comment by fengzhaowang** [comment]
![image](https://github.com/apache/rocketmq-mqtt/assets/56420502/5dc295da-217f-4b87-ba2e-979f9d0c963c)
出现这个问题我寻找代码是下面代码导致的，7001端口接收的消息的PubTopic为空，导致空指针，如下：
![企业微信20240701-134157](https://github.com/apache/rocketmq-mqtt/assets/56420502/3c9fe728-ed74-4a04-bf8a-bfbe484d148a)
![企业微信20240701-134253](https://github.com/apache/rocketmq-mqtt/assets/56420502/fcbb1096-a191-4bf6-88b5-e7fe99587375)
我暂时解决的办法为：
![企业微信20240701-134624](https://github.com/apache/rocketmq-mqtt/assets/56420502/59d1c499-a433-4b9b-8fdd-f9022275c669)
暂时没有报错，业务也正常运行，不知道是否可以这样做？

**Comment by DongyuanPan** [comment]
> ![image](https://private-user-images.githubusercontent.com/56420502/344557129-5dc295da-217f-4b87-ba2e-979f9d0c963c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjU3NzYsIm5iZiI6MTcxOTgyNTQ3NiwicGF0aCI6Ii81NjQyMDUwMi8zNDQ1NTcxMjktNWRjMjk1ZGEtMjE3Zi00Yjg3LWJhMmUtOTc5ZjlkMGM5NjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA5MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNDFhZmViZTdmOTdlNDYwZDNkNjczZGQ1NGIyMDQ3MWRhNGJiNjFmODM0MTM1OTI2OWE4OWIzMDc5MzczNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ow9Aeo2aYhI43DtkxqjQN-DfXJyRvQboY7KoNJIkWoY) 出现这个问题我寻找代码是下面代码导致的，7001端口接收的消息的PubTopic为空，导致空指针，如下： ![企业微信20240701-134157](https://private-user-images.githubusercontent.com/56420502/344556802-3c9fe728-ed74-4a04-bf8a-bfbe484d148a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjU3NzYsIm5iZiI6MTcxOTgyNTQ3NiwicGF0aCI6Ii81NjQyMDUwMi8zNDQ1NTY4MDItM2M5ZmU3MjgtZWQ3NC00YTA0LWJmOGEtYmZiZTQ4NGQxNDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA5MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTRmYTAwNTI4OWI3MGMyMDNlMzQzNTgyMzZlNzgxNjdkZDVmODRiNGE1YzczY2EzN2Y5YTA0NGZlNWE5OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EE4IMozzO-RWctOn0H1AQIQFF0i8BWRUhIXscY4BRMg) ![企业微信20240701-134253](https://private-user-images.githubusercontent.com/56420502/344556845-fcbb1096-a191-4bf6-88b5-e7fe99587375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjU3NzYsIm5iZiI6MTcxOTgyNTQ3NiwicGF0aCI6Ii81NjQyMDUwMi8zNDQ1NTY4NDUtZmNiYjEwOTYtYTE5MS00YmY2LTg4YjUtZTdmZTk5NTg3Mzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA5MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMGZlMmM3OWRjMDg2NzUyMmNlZTk2Y2E4OTYxOWRhMTVjYjZhOWUzZDc5OWZhYzI4NDZhNjZlNzg5NTdkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xdBTk2EcMIfDy7tWR4qEanzW5whT7_9ECLL3qxCJYhc) 我暂时解决的办法为： ![企业微信20240701-134624](https://private-user-images.githubusercontent.com/56420502/344557479-59d1c499-a433-4b9b-8fdd-f9022275c669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjU3NzYsIm5iZiI6MTcxOTgyNTQ3NiwicGF0aCI6Ii81NjQyMDUwMi8zNDQ1NTc0NzktNTlkMWM0OTktYTQzMy00YjliLThmZGQtZjkwMjIyNzVjNjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA5MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OTQ1YTYwM2NiZGRiYjM1NTJkOTUyYTIyNzJiMjE2NmI0NzE4MmFkMjY5ZGM3YjZjOGZhYWQ3NTQ2N2RjMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.utBpAuYb1J5iqLSQVkp3yionz-o1geMSy_jXm8G55iQ) 暂时没有报错，业务也正常运行，不知道是否可以这样做？

plz use rocketmq-mqtt develop branch to have a try

**Comment by DongyuanPan** [comment]
PubTopic is seted in NotifyManager#setPubTopic(), You can check in there Why is PubTopic empty

**Comment by DongyuanPan** [comment]
maybe same as https://github.com/apache/rocketmq-mqtt/issues/221 , check lmq config in rmq?

**Comment by fengzhaowang** [comment]
有重试停止mqtt的meta和mqtt服务，继续向rmq中发消息，发完消息再启动mqtt吗

**Comment by DongyuanPan** [comment]
> 有重试停止mqtt的meta和mqtt服务，继续向rmq中发消息，发完消息再启动mqtt吗

yes

**Comment by fengzhaowang** [comment]
使用rocketmq 5.1.4 + RocketMQ-MQTT develop branch已解决问题
