### ISSUE TITLE
Practice sharing

### ISSUE THREAD

**Issue by dongbaibai** [apache/rocketmq-mqtt#35]
We use the same approach for communication between applications and services
but not by a gateway
we use a mqtt client to send message from rocketmq to mqtt broker
by a gateway seem to reduce number of communication between mqtt-client and mqtt-broker

**Comment by tianliuliu** [comment]
> We use the same approach for communication between applications and services but not by a gateway we use a mqtt client to send message from rocketmq to mqtt broker by a gateway seem to reduce number of communication between mqtt-client and mqtt-broker

consume rocketmq and then use mqtt client send to mqtt broker?  Can you express it more clearly, I don't know if I understand it right?

**Comment by ferrirW** [comment]
It seems to be about embedding the MQTT protocol into the RocketMQ Broker?

then communication number 
from: 
mqtt-publisher -> mqtt-broker -> rmq-broker -> mqtt-broker -> mqtt-subscriber 
to: 
mqtt-publisher -> rmq-broker -> mqtt-subscriber

**Comment by tianliuliu** [comment]
> 



> It seems to be about embedding the MQTT protocol into the RocketMQ Broker?
> 
> then communication number from: mqtt-publisher -> mqtt-broker -> rmq-broker -> mqtt-broker -> mqtt-subscriber to: mqtt-publisher -> rmq-broker -> mqtt-subscriber

That requires rmq itself to have the ability to process mqtt protocol messages, rmq becomes more bloated, and needs to perceive the mqtt business layer
