### ISSUE TITLE
ChannelInfo class when the clear() method is called, NPE will be triggered here

### ISSUE THREAD

**Issue by tianliuliu** [apache/rocketmq-mqtt#53]
in branch main  
org.apache.rocketmq.mqtt.cs.channel.ChannelInfo
![image](https://user-images.githubusercontent.com/13758677/161933076-fcb56c38-74eb-45aa-b973-8e116ff4e354.png)

![image](https://user-images.githubusercontent.com/13758677/161925332-bad398ff-6ff9-4249-88c5-0de636a7e6da.png)

boolean(null) will case NPE

**Comment by YxAc** [comment]
That's my mistake, thanks for your time and sorry for the trouble. @tianliuliu @duhenglucky

**Comment by tianliuliu** [comment]
> That's my mistake, thanks for your time and sorry for the trouble. @tianliuliu @duhenglucky

it does not matter, you are welcome.
