### ISSUE TITLE
It is necessary to define a subscription storage interface

### ISSUE THREAD

**Issue by pingww** [apache/rocketmq-mqtt#65]
According to the [MQTT protocol  specifications](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf) , Session stores not only messages but also subscriptions, 

![image](https://user-images.githubusercontent.com/2748647/163553920-4fa2c2fe-615b-4479-a915-fb1d64505bf6.png)

which actually is  a persist KV. Currently RocketMQ does not have KV persistence, so we need to define an external storage interface.

**Comment by hill007299** [comment]
Maybe we could build a Rocksdb into the rocketmq store and enable KV

**Comment by pingww** [comment]
> Maybe we could build a Rocksdb into the rocketmq store and enable KV

Many scenarios, not just MQTT scenarios, require RocketMQ to have a built-in persistence metadata(kv) storage capability

**Comment by YxAc** [comment]
> > Maybe we could build a Rocksdb into the rocketmq store and enable KV
> 
> Many scenarios, not just MQTT scenarios, require RocketMQ to have a built-in persistence metadata(kv) storage capability

+1, but,
what is the location of the KV storage here?  Is it positioned as local persistence or remote durable storage? 

Take the subscription to discuss, maybe the Topic built-in RocketMQ is enough or convenient to use? also because the topic can be a centralized storage compares to Rocksdb.

**Comment by pingww** [comment]
> 

The subscription structure is about <clientid, subscription>   just like a KV Query but must be durable. Topic built-in RocketMQ may be or not realized. Rocksdb is just a single local persistence, the upper layer also needs to realize the global KV query capability, such as sharding.

**Comment by pingww** [comment]
> 

The subscription structure is about <clientid, subscription>   just like a KV Query but must be durable. Topic built-in RocketMQ may be or not realized. Rocksdb is just a single local persistence, the upper layer also needs to realize the global KV query capability, such as sharding.

**Comment by YxAc** [comment]
yes, the global KV query capability is necessary

**Comment by tianliuliu** [comment]
RocketMQ has a built-in persistence metadata(kv) storage capability which is the best way and does not introduce external dependencies

**Comment by azhsmesos** [comment]
So the question is should we introduce the rocksDB engine directly to RocketMQ or should we write RocketMQ own kv storage tool

**Comment by azhsmesos** [comment]
I have an idea that I want to implement it in this way. Referring to the LSM tree model, write data in sequence and build an index structure. The index only stores the offset of the key on the disk, and an extra byte is added after the key to store the offset of the corresponding value on the disk. Consider deleting and compaction operations, such as the garbage debris that results from a remove operation and how to compaction a memory block。 is a simple idea
