### ISSUE TITLE
To support Will Message Feature

### ISSUE THREAD

**Issue by pingww** [apache/rocketmq-mqtt#69]
**Will Message** is MQTT's ability to gracefully send wills to third parties for devices that may be unexpectedly disconnected. The Current version supports the MQTT 3.1.1 protocol, but the **Will Message** feature in this version is not yet supported. So we are discussing plans to support this feature.

**Comment by DongyuanPan** [comment]
I'd love to implement this feature, can you assign me？

**Comment by pingww** [comment]
> I'd love to implement this feature, can you assign me？

welcome

**Comment by tianliuliu** [comment]
> I'd love to implement this feature, can you assign me？

ping @ShannonDing

**Comment by DongyuanPan** [comment]
it can be closed @ShannonDing
