### ISSUE TITLE
A question about qos level 

### ISSUE THREAD

**Issue by shendongsd** [apache/rocketmq-mqtt#92]
Does the QoS of messages sent to consumers not need to be downgraded?
![image](https://user-images.githubusercontent.com/23067207/167060300-d84abcbc-3c8a-471b-b3e0-684589ea335f.png)

**Comment by YxAc** [comment]
it indeed need downgrade to Min<pub, sub> which is described by mqtt-v3.1.1:
`"The QoS of Payload Messages sent in response to a Subscription MUST be the minimum of the QoS of the originally published message and the maximum QoS granted by the Server"`

**Comment by shendongsd** [comment]
> it indeed need downgrade to Min<pub, sub> which is described by mqtt-v3.1.1: `"The QoS of Payload Messages sent in response to a Subscription MUST be the minimum of the QoS of the originally published message and the maximum QoS granted by the Server"`

**Comment by pingww** [comment]
Currently server support QoS0、QoS1、QoS2
